name: Deploy PHP Project

on:
  push:
    branches:
      - master  # Déclenche l'action sur la branche master
  pull_request:
    branches:
      - master  # Déclenche aussi pour les pull requests sur master

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le pipeline

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Récupère le code source depuis GitHub

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Choisissez la version PHP à utiliser (vous pouvez aussi choisir une version plus récente)
        extensions: mbstring, bcmath  # Liste des extensions PHP nécessaires

    - name: Install dependencies with Composer
      run: |
        curl -sS https://getcomposer.org/installer | php  # Installe Composer
        php composer.phar install  # Installe les dépendances via Composer

    - name: Run tests (optional)
      run: php vendor/bin/phpunit --configuration phpunit.xml.dist  # Si vous avez des tests, les exécuter ici

    - name: Deploy to Server via SSH (optional)
      if: success()  # Assurez-vous que l'étape précédente a réussi
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null  # Ajoute la clé SSH
        ssh -o StrictHostKeyChecking=no $USER@$SERVER_HOST "cd /var/www/html && git pull origin master"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Stocker la clé SSH en tant que secret GitHub
        USER: ${{ secrets.SERVER_USER }}  # Utilisateur pour se connecter au serveur
        SERVER_HOST: ${{ secrets.SERVER_HOST }}  # Hôte du serveur

